### ISSUE TITLE
one can view the dashboard  after the log out.

### ISSUE THREAD

**Issue by Guvi-pugazh** [padegalmadhuri/covid19-visualizer-padegalmadhuri#1]
Steps followed:

1. created a new account by pressing the signup button.
2. logged in using the mail id and password.
3. once it's logged into the application, I can view the dashboard.
4. I have copied the URL of the dashboard page.
              [URL](https://covid19-visualizer-padegalmadhuri.netlify.app/#/dashboard)
5. log out by pressing the log out button.
6. I have entered the dashboard URL, it's allowing me to view the dashboard.

**Comment by padegalmadhuri** [comment]
https://vibrant-chandrasekhar-5e3093.netlify.app/#/
I have updatedGuard
